package com.exam;
// Generated Jun 11, 2019 12:18:53 PM by Hibernate Tools 4.3.1



/**
 * Bkash generated by hbm2java
 */
public class Bkash  implements java.io.Serializable {


     private int cid;
     private String mobileno;
     private String amount;

    public Bkash() {
    }


    public Bkash( String mobileno, String amount) {
       this.cid = cid;
       this.mobileno = mobileno;
       this.amount = amount;
    }
   
    public int getCid() {
        return this.cid;
    }
    
    public void setCid(int cid) {
        this.cid = cid;
    }
    public String getMobileno() {
        return this.mobileno;
    }
    
    public void setMobileno(String mobileno) {
        this.mobileno = mobileno;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }




}


