package com.exam;
// Generated Jun 11, 2019 12:18:53 PM by Hibernate Tools 4.3.1

import javax.validation.constraints.Pattern;
import org.hibernate.validator.constraints.NotEmpty;




/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer id;
     private String name;
        @NotEmpty
    @Pattern(regexp = "[a-zA-Z0-9]+[@][a-z]+[.][a-z]{2,3}$", message = "email  or password is not valid")
     private String email;
        
     private String passwsord;
        
   
     private String gender;
    private String password;

    public User() {
    }

    public User(String name, String email, String password, String gender) {
       this.name = name;
       this.email = email;
       this.password = password;
       this.gender = gender;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }




}


