package com.exam;
// Generated Jun 11, 2019 12:18:53 PM by Hibernate Tools 4.3.1



/**
 * Bank generated by hbm2java
 */
public class Bank  implements java.io.Serializable {


     private int accountno;
     private String branchname;
     private String amount;

    public Bank() {
    }

	
    public Bank(int accountno) {
        this.accountno = accountno;
    }
    public Bank(int accountno, String branchname, String amount) {
       this.accountno = accountno;
       this.branchname = branchname;
       this.amount = amount;
    }
   
    public int getAccountno() {
        return this.accountno;
    }
    
    public void setAccountno(int accountno) {
        this.accountno = accountno;
    }
    public String getBranchname() {
        return this.branchname;
    }
    
    public void setBranchname(String branchname) {
        this.branchname = branchname;
    }
    public String getAmount() {
        return this.amount;
    }
    
    public void setAmount(String amount) {
        this.amount = amount;
    }




}


