package com.exam;
// Generated Jun 11, 2019 12:18:53 PM by Hibernate Tools 4.3.1



/**
 * Car generated by hbm2java
 */
public class Car  implements java.io.Serializable {


     private int id;
     private String carname;
     private String img;
     private String carbrand;
     private String price;
     private String carcolour;
     private String status;
     private String fare;

    public Car() {
    }

    public Car(int id, String carname,String img, String carbrand, String price, String carcolour, String status, String fare) {
        this.id = id;
        this.carname = carname;
        this.img = img;
        this.carbrand = carbrand;
        this.price = price;
        this.carcolour = carcolour;
        this.status = status;
        this.fare = fare;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCarname() {
        return carname;
    }

    public void setCarname(String carname) {
        this.carname = carname;
    }
    
    public String getImg() {
        return img;
    }

    public void setImg(String img) {
        this.img = img;
    }

    

    public String getCarbrand() {
        return carbrand;
    }

    public void setCarbrand(String carbrand) {
        this.carbrand = carbrand;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getCarcolour() {
        return carcolour;
    }

    public void setCarcolour(String carcolour) {
        this.carcolour = carcolour;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getFare() {
        return fare;
    }

    public void setFare(String fare) {
        this.fare = fare;
    }


}


