package com.exam;
// Generated Jun 11, 2019 12:18:53 PM by Hibernate Tools 4.3.1



/**
 * Valid generated by hbm2java
 */
public class Valid  implements java.io.Serializable {


     private int cid;
     private String name;
     private String cardno;
     private String password;
     private String expiredate;
     private String amount;

    public Valid() {
    }

    public Valid(int cid, String name, String cardno, String password, String expiredate,String amount) {
        this.cid = cid;
        this.name = name;
        this.cardno = cardno;
        this.password = password;
        this.expiredate = expiredate;
        this.expiredate = amount;
    }

    public int getCid() {
        return cid;
    }

    public void setCid(int cid) {
        this.cid = cid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getCardno() {
        return cardno;
    }

    public void setCardno(String cardno) {
        this.cardno = cardno;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getExpiredate() {
        return expiredate;
    }

    public void setExpiredate(String expiredate) {
        this.expiredate = expiredate;
    }

    public String getAmount() {
        return amount;
    }

    public void setAmount(String amount) {
        this.amount = amount;
    }


   
}


